version: "2"
services:
  app:
    container_name: "cooking"
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: "mongodbtest"
    image: mongo:3.0.6
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub2
    ports:
      - "5555:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub2
      - HUB_PORT_4444_TCP_PORT=4444

  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub2
      - HUB_PORT_4444_TCP_PORT=4444
